"""add fen column to games table

Revision ID: 5f87d88f6e96
Revises: a77f31de3d97
Create Date: 2023-04-08 15:12:42.623601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f87d88f6e96'
down_revision = 'a77f31de3d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fen', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('fen')

    # ### end Alembic commands ###
